"""
ApiClient for Event Booking SDK.
Auto-generated by OpenAPI Generator CLI — do not edit manually.
"""
import requests
from .configuration import Configuration


class ApiClient:
    def __init__(self, configuration=None):
        if configuration is None:
            configuration = Configuration()
        self.configuration = configuration
        self.base_url = configuration.host
        self.session = requests.Session()
        self.session.headers.update({"Content-Type": "application/json"})

    def call_api(self, method, path, body=None, params=None):
        url = f"{self.base_url}{path}"
        headers = None
        if self.configuration.access_token:
            headers = {"Authorization": f"Bearer {self.configuration.access_token}"}
        response = self.session.request(method, url, json=body, params=params, headers=headers)
        response.raise_for_status()
        if response.content:
            return response.json()
        return None
