"""
Configuration class for Event Booking SDK.
Auto-generated by OpenAPI Generator CLI — do not edit manually.
"""


class Configuration:
    def __init__(self, host="http://localhost:8000"):
        self.host = host
        self.api_key = {}
        self.api_key_prefix = {}
        self.username = ""
        self.password = ""
        self.access_token = ""
        self.temp_folder_path = None
        self.safe_chars_for_path_param = ""
        self.debug = False

    @property
    def base_path(self):
        return self.host
