"""
Booking model.
Auto-generated by OpenAPI Generator CLI — do not edit manually.
"""
from typing import Optional


class Booking:
    def __init__(
        self,
        id: int,
        event_id: int,
        user_name: str,
        booking_date: str,
        user_id: Optional[int] = None,
        number_of_tickets: int = 1,
    ):
        self.id = id
        self.event_id = event_id
        self.user_name = user_name
        self.booking_date = booking_date
        self.user_id = user_id
        self.number_of_tickets = number_of_tickets

    def __repr__(self):
        return (f"Booking(id={self.id}, event_id={self.event_id}, "
                f"user_name={self.user_name!r})")

    @classmethod
    def from_dict(cls, data: dict):
        return cls(
            id=data["id"],
            event_id=data["event_id"],
            user_name=data["user_name"],
            booking_date=data["booking_date"],
            user_id=data.get("user_id"),
            number_of_tickets=data.get("number_of_tickets", 1),
        )
