"""
Event model.
Auto-generated by OpenAPI Generator CLI — do not edit manually.
"""
from datetime import datetime
from typing import Optional


class Event:
    def __init__(self, id: int, name: str, description: Optional[str],
                 total_seats: int, available_seats: int, date: str):
        self.id = id
        self.name = name
        self.description = description
        self.total_seats = total_seats
        self.available_seats = available_seats
        self.date = date

    def __repr__(self):
        return (f"Event(id={self.id}, name={self.name!r}, "
                f"available_seats={self.available_seats}/{self.total_seats})")

    @classmethod
    def from_dict(cls, data: dict):
        return cls(
            id=data["id"],
            name=data["name"],
            description=data.get("description"),
            total_seats=data["total_seats"],
            available_seats=data["available_seats"],
            date=data["date"],
        )
